### ISSUE TITLE
RHEL book contains duplicate IDs

### ISSUE THREAD

**Issue by kowen-rh** [red-hat-openjdk/docs#1]
The RHEL book builds, but presents warnings related to duplicate IDs in some of the procedures which are included more than once via `include::[]`. We should use `<id>_{context}` when creating anchors to assign unique IDs and prevent these issues.

**Comment by kowen-rh** [comment]
Looks like the duplicate IDs are from including `modules/proc-rhel-setting-java-home-env-variable.adoc` multiple times.

Should this be a procedure or a snippet? Either way, we need to make modifications to the docs.

**Comment by kowen-rh** [comment]
After some discussion, it looks like we should rewrite the `JAVA_HOME` information as a reusable snippet instead of a procedure.

**Comment by ncbaratta** [comment]
Did I fix this with my last updates?

**Comment by kowen-rh** [comment]
Yes, this issue seems to be resolved. Thank you!
