### ISSUE TITLE
Installing the Java Development Kit via yum on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#12]
QE by @judovana  

1.1. Installing the Java Development Kit via yum on Red Hat Enterprise Linux

Step 2: If customer has installed also JDK 8 or anything else on his system (default system jdk will probably be present), and it is set up as default in alternatives (usually is, unless customer manually changes it), this does not apply. He will get version of javac with highest priority which is JDK 8. Customer needs to run:

/usr/lib/jvm/java-11/bin/javac -version
javac 11.0.3

Run that to always get javac version of JDK 11 or set it manually in alternatives.

**Comment by jerboaa** [comment]
> QE by @judovana
> 
> 1.1. Installing the Java Development Kit via yum on Red Hat Enterprise Linux
> 
> Step 2: If customer has installed also JDK 8 or anything else on his system (default system jdk will probably be present), and it is set up as default in alternatives (usually is, unless customer manually changes it), this does not apply. He will get version of javac with highest priority which is JDK 8. Customer needs to run:
> 
> /usr/lib/jvm/java-11/bin/javac -version
> javac 11.0.3
> 
> Run that to always get javac version of JDK 11 or set it manually in alternatives.

While that's true the procedure tries to explain this:

```
Starting from nothing, I want JDK 8. How do I get it installed?
```

In those cases they don't necessarily want to know what happens if *both* JDKs are installed. That's what 3.1 tries to explain. @ncbaratta any recommendations? Would a note be helpful here?

**Comment by ncbaratta** [comment]
Maybe a note that links to the later section to let the user know that there is an answer to the other model.

Maybe a prerequisite as well stating that nothing else should be installed?
