### ISSUE TITLE
1.3. Installing the Java Runtime Environment via yum on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#14]
QE by @judovana  

1.3. Installing the Java Runtime Environment via yum on Red Hat Enterprise Linux
OpenJDK 11 for Windows can be installed using the system package manager yum.
- jdk11 here, jdk8 afterwards down there. Very confusing, and again what is with the windows?

There is a typo in “prequisites” (should be prerequisites)

Run the relevant yum command for installing the package. For example: java-1.8.0-openjdk for JDK 8
# yum install java-8-openjdk
In the step one, you correctly point out that java-1.8.0-openjdk. Why are you then installing java-8-openjdk? This package does not exist!

**Comment by zekaguilar** [comment]
Just fixed please check the PR. Thanks

**Comment by jerboaa** [comment]
this one? https://github.com/jerboaa/RH-OpenJDK-Docs/pull/1 It ended up being a PR against the wrong upstream repo. Should be: https://github.com/red-hat-openjdk/docs
