### ISSUE TITLE
1.4. Installing the JRE with the archive bundle on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#15]
QE by @judovana  

1.4. Installing the JRE with the archive bundle on Red Hat Enterprise Linux
Again - are you sure about the zips and windows?

Step 5: 
Java version output might again return the default (8) jre instead of the installed jre, if you use it like this.

Step 6: 
In order to persist the PATH variable setting use these instructions: `<add-link-to-RHEL-bashrc-path-link>`
Forgotten link?

Step 8:
There is the same issue with the opt.

**Comment by zekaguilar** [comment]
In step 5, won't be executed first the already added path (jres/<major_version>/bin) instead of the default one ? 
I don't know the order of the PATH here. do you know @jerboaa ?
In step 6, @ncbaratta that constant is missing ?

**Comment by zekaguilar** [comment]
Step 8 is based on a KCB, should we override it @ncbaratta  ?

**Comment by jerboaa** [comment]
> In step 5, won't be executed first the already added path (jres/<major_version>/bin) instead of the default one ?
> I don't know the order of the PATH here. do you know @jerboaa ?

Jiri's point was that we originally documented **appending** to the `PATH` variable. We should be recommending **prepending**, I think.

So

```
export PATH=/path/to/zip/bin:$PATH
```

rather than:

```
export PATH=$PATH:/path/to/zip/bin
```

**Comment by ncbaratta** [comment]
@zekaguilar I'm not sure what the constant we need in step 6 is ...

**Comment by zekaguilar** [comment]
@ncbaratta 
**add-link-to-RHEL-bashrc-path-link**

I did not found that file in the project

**Comment by zekaguilar** [comment]
> @ncbaratta
> **add-link-to-RHEL-bashrc-path-link**
> 
> I did not found that file in the project

Nevermind I found it :D

**Comment by zekaguilar** [comment]
Fixed and PR requested
