### ISSUE TITLE
1.5. Installing multiple major versions of OpenJDK

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#16]
QE by @judovana  

1.5. Installing multiple major versions of OpenJDK

Please use OpenJDK or JDK instead of Java. (e.g. require different JDK versions). I don’t think we have a commercial license to use “Java”. 

I am unable to check the procedure but it looks okay. But why don’t we use the very same procedure for 1.1 and 1.3? It is just the same, but for multiple installs we need to enable repo? I don’t follow. 

And why would they look for it in RHCP in the first place, when you already show them which repos they need and also those repos should be available by default? Very confusing.

**Comment by mgm3746** [comment]
Good points. I have updated per @judovana 's suggestions and submitted PRs.
