### ISSUE TITLE
1.6. Installing multiple minor versions of OpenJDK on RHEL

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#17]
QE by @judovana  

1.6. Installing multiple minor versions of OpenJDK on RHEL

Step 1. - are you sure about that? 

java-11-openjdk-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-demo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-demo-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-devel-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-devel-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-headless-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-headless-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-javadoc-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-javadoc-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-javadoc-zip-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-javadoc-zip-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-jmods-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-jmods-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-src-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-src-slowdebug-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-debugsource-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-devel-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-devel-slowdebug-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-headless-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-headless-slowdebug-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download)
java-11-openjdk-slowdebug-debuginfo-11.0.3.7-3.el8.x86_64.rpm (info) (download) 

This is what we have on intel. Customer should be aware there are number of packages and if he wants different minor versions, he should specify all (1-n)of the packages he wants to install, not only three base pkgs.

**Comment by mgm3746** [comment]
@judovana 

>Step 1. - are you sure about that?

I did verify it. It comes from a KCS that is in a verified state and looks to be pretty well vetted:
https://access.redhat.com/solutions/3508401

**Comment by mgm3746** [comment]
Added mention of other OpenJDK packages and submitted PR.

**Comment by jerboaa** [comment]
Has this been fixed and we can close it?

**Comment by ncbaratta** [comment]
I think it has.
