### ISSUE TITLE
2.1. Updating OpenJDK using yum on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#18]
QE by @judovana  

2.1. Updating OpenJDK using yum on Red Hat Enterprise Linux
The OpenJDK 11 for Windows RPM-based installer can be updated using the system package manager yum.
Are you sure about that Windows? 
Procedure
Check the current OpenJDK 11 for Windows version.
Are you sure about that Windows?

There is a typo in “prequisites” (should be prerequisites)

**Comment by zekaguilar** [comment]
Typo fixed
