### ISSUE TITLE
2.2. Updating OpenJDK for RHEL using an archive

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#19]
QE by @judovana  

2.2. Updating OpenJDK for RHEL using an archive

OpenJDK 11 for Windows can be manually installed using an archive. 
are you sure about that Windows?
Are you sure about ZIPs?

The hyperlinks JDK and JRE do not work. 
There is a typo in “prequisities” (should be prerequisites)

**Comment by jerboaa** [comment]
> QE by @judovana
> 
> 2.2. Updating OpenJDK for RHEL using an archive
> 
> OpenJDK 11 for Windows can be manually installed using an archive.
> are you sure about that Windows?
> Are you sure about ZIPs?

These are issues with the attributes files where they are defined for windows 11 openjdk and zip.

> The hyperlinks JDK and JRE do not work.
> There is a typo in “prequisities” (should be prerequisites)

Fixed with #34

**Comment by jerboaa** [comment]
> QE by @judovana
> 
> 2.2. Updating OpenJDK for RHEL using an archive
> 
> OpenJDK 11 for Windows can be manually installed using an archive.
> are you sure about that Windows?
> Are you sure about ZIPs?

These are issues with the attributes files where they are defined for windows 11 openjdk and zip.

> The hyperlinks JDK and JRE do not work.
> There is a typo in “prequisities” (should be prerequisites)

Fixed with #34
