### ISSUE TITLE
3.1. Selecting a specific JDK on Red Hat Enterprise Linux installed with RPMs

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#20]
QE by @judovana  

3.1. Selecting a specific JDK on Red Hat Enterprise Linux installed with RPMs

Have multiple JDKs installed on your system using the yum package manager.
Not true, having JRE is enough. Set your terminology straight - if you use JDK for any java installation (JRE+SDK), please change JDK from chapters above to SDK. This is a mess.

Selecting the JDK by using this approach changes the default java system wide and requires root privileges
Selecting the JRE  - you dont need JDK to change java. JRE=java, SDK(JDK)=javac

Step 1:
- Please replace Java for JDK/JRE

Alternatives --display java/javac would provide perhaps more information about what are you exactly setting. 

The hyperlinks do not work.

**Comment by jerboaa** [comment]
> 3.1. Selecting a specific JDK on Red Hat Enterprise Linux installed with RPMs
> 
> Have multiple JDKs installed on your system using the yum package manager.
> Set your terminology straight - if you use JDK for any java installation (JRE+SDK), please change JDK from chapters above to SDK. This is a mess.

Agreed. There are a couple of acronyms we need to define globally and use consistently throughout. @ncbaratta I suggest we create an overarching issue for this and change it globally once we've reached consensus on the terms which we should use throughout (currently the docs is a first write-up by different people; consistency is not great, yet).

As to the `JDK` vs. `JRE` vs. `SDK` comment: I'd try not to use Software Development Kit (SDK). It's the more general term than Java Development Kit (JDK), and we are clearly in an Java (OpenJDK) context in those docs. Note that there is a .NET SDK as well.

So as far as a glossary is concerned I'd suggest these entries. I'm not very good at this, so suggestions to improve it most welcome!

```
Java
   The java binary part of the JRE for Java 8, or JDK for Java 11, respectively

JRE
   Java Runtime Environment. The runtime environment, not including development tools, for the
   Java Platform.

JDK
   Java Development Kit. The Java Runtime Environment plus tools needed for compiling
   and developing Java applications.
```

> Selecting the JDK by using this approach changes the default java system wide and requires root privileges
> Selecting the JRE - you dont need JDK to change java. JRE=java, SDK(JDK)=javac

I'll update the docs to switch `java` *and* `javac` as both can be switched independently, yet the title is about changing both `java` and `javac`. Keyword, specific **JDK**

> Step 1:
> 
>     * Please replace Java for JDK/JRE
> 

Those are user docs, and I'm not sure if it's clearer to use Java or `JRE`. I'd argue that most users would likely want to change the java binary, thus writing "Java" seems more to the point. Not all of them might know what JRE is.

> Alternatives --display java/javac would provide perhaps more information about what are you exactly setting.

Remember, there is a balance to strike how much details we should provide. There are many knobs one can turn. Not necessarily everybody needs to know all the info. Writing concise, yet well skimmable docs is hard. I'll think some more about how we can improve this.

> The hyperlinks do not work.

I'll fix that.
