### ISSUE TITLE
3.2. Selecting a specific JDK on Red Hat Enterprise Linux non-interactively

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#21]
QE by @judovana  

3.2. Selecting a specific JDK on Red Hat Enterprise Linux non-interactively

This is useful for administrators who have root privileges on a Red Hat Enterprise Linux system and need to switch the default Java on many systems in an automated way.
	- JDK please, not java
Have multiple JDKs installed - does not work
Know the desired Java major version which…
	- JDK please

Step 1:
Set the PKG_NAME variable to the Java version you’d like to switch to. In our example, that’s java-11-openjdk for Java 11. Then switch to the Java selection using the alternatives --set command.
OpenJDK or JDK please, not Java

Step 2.
Replace Java for JRE or java command, not Java (trademark of oracle)

If you wanted to switch to Java 8, set PKG_NAME=java-1.8.0-openjdk, instead.
 	- OpenJDK 8, please, not Java

I really do not understand why this script - it is not correct and it is ugly. 

Imagine a situation, if we have two minor versions installed with java-11-openjdk family. Then you get multiple strings in the JAVA_TO_SELECT output and the command fails.

I would assume customer or his admin is skilled enough to learn, which java he wants to pick and call the command directly, or think about his own script. If you want to give him a hint, tell him he needs to go for family from alternatives --display output.

**Comment by jerboaa** [comment]
> 3.2. Selecting a specific JDK on Red Hat Enterprise Linux non-interactively
> Have multiple JDKs installed - does not work

Can the reporter be more specific, please? What does not work? Installing multiple JDKs?

**Comment by pmikova** [comment]
Hi,
these were copied from my google doc. That "Have multiple JDK installed" was a hyper text link, that was not working in the document. Sorry for the confusion, in the original doc it was linked to the non-working link.

**Comment by jerboaa** [comment]
> QE by @judovana
> 
> 3.2. Selecting a specific JDK on Red Hat Enterprise Linux non-interactively
> 
> This is useful for administrators who have root privileges on a Red Hat Enterprise Linux system and need to switch the default Java on many systems in an automated way.
> - JDK please, not java
> Have multiple JDKs installed - does not work
> Know the desired Java major version which…
> - JDK please
> 
> Step 1:
> Set the PKG_NAME variable to the Java version you’d like to switch to. In our example, that’s java-11-openjdk for Java 11. Then switch to the Java selection using the alternatives --set command.
> OpenJDK or JDK please, not Java
> 
> Step 2.
> Replace Java for JRE or java command, not Java (trademark of oracle)
> 
> If you wanted to switch to Java 8, set PKG_NAME=java-1.8.0-openjdk, instead.
> - OpenJDK 8, please, not Java
> 
> I really do not understand why this script - it is not correct and it is ugly.

It's guidance to give users an idea how they could go about switching the system JDK on many systems. Note that it's not meant to be bullet proof. It covers the basic case of changing from JDK 8 (default) to JDK 11.

> Imagine a situation, if we have two minor versions installed with java-11-openjdk family. Then you get multiple strings in the JAVA_TO_SELECT output and the command fails.

Thanks, good point.

> I would assume customer or his admin is skilled enough to learn, which java he wants to pick and call the command directly, or think about his own script. If you want to give him a hint, tell him he needs to go for family from alternatives --display output.

I've added this in the info note.
