### ISSUE TITLE
3.6. Configuring OpenJDK to run with customized heap size

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#25]
QE by @judovana  

3.6. Configuring OpenJDK to run with customized heap size
OpenJDK 11 for Windows can be configured to use a customized heap size.
This is getting old, come on

Prequisites
Should be prerequisites
Installed Java Runtime	
JRE, please don’t use Java, we provide OpenJDK (JRE+SDK) not Java
Procedure
Run the application by adding maximum heap size option to your java command line. For example to set the maximum heap size to 100 megabytes use the -Xmx100m option.
Java command line -  Try something like java command, or java binary please

**Comment by jerboaa** [comment]
> 3.6. Configuring OpenJDK to run with customized heap size
> OpenJDK 11 for Windows can be configured to use a customized heap size.
> This is getting old, come on

String `OpenJDK 11 for Windows` comes from `{comp}` attribute. That's for @ncbaratta to fix. Attributes need windows/rhel specific values.

> Prequisites
> Should be prerequisites
> Installed Java Runtime
> JRE, please don’t use Java, we provide OpenJDK (JRE+SDK) not Java

I've opted for `Java Runtime Environment (JRE)`. We definitely need some consistency on that point, though. cc @ncbaratta

> Procedure
> Run the application by adding maximum heap size option to your java command line. For example to set the maximum heap size to 100 megabytes use the -Xmx100m option.
> Java command line - Try something like java command, or java binary please

Fixed in #32.
