### ISSUE TITLE
Add a glossary for reference

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#39]
Asked by @jerboaa : "What does JRE/JDK/SDK stand for? I think we need a glossary with links."

**Comment by ncbaratta** [comment]
It might make sense to put this in a documentation conventions section at the beginning. And example of this can be seen here: https://access.redhat.com/documentation/en-us/red_hat_amq/7.3/html/getting_started_with_amq_broker/overview-getting-started#document_conventions

**Comment by ncbaratta** [comment]
Define:

- OpenJDK
- JDK
- JRE - mention that it’s removed in Java 11
- MSI

**Comment by jerboaa** [comment]
@ncbaratta I can work on that, but would need some guidance where the glossary should be added. Could you perhaps add a stub file in the tree and we fill it with content?

**Comment by ncbaratta** [comment]
Like this? https://github.com/red-hat-openjdk/docs/blob/master/modules/ref-dictionary.adoc

**Comment by jerboaa** [comment]
> Like this? https://github.com/red-hat-openjdk/docs/blob/master/modules/ref-dictionary.adoc

Yes, thanks!

**Comment by akashche** [comment]
`.MSI` is the filename extension of Windows Installer (previously known as Microsoft Installer) packages.
