### ISSUE TITLE
Installation suggestion

### ISSUE THREAD

**Issue by ncbaratta** [red-hat-openjdk/docs#9]
QE by @judovana  

After reading this draft, I recommend the documentarist to read this: https://developers.redhat.com/blog/2018/11/05/migrating-from-oracle-jdk-to-openjdk-on-red-hat-enterprise-linux-what-you-need-to-know/
It contains a very nice guide about how to install the red hat openjdk (but with the migration from oracle extras). In general a very nice source of information for this guide.

**Comment by mgm3746** [comment]
I read the article and added content related to supportability of old minor versions. Was there something more?

**Comment by jerboaa** [comment]
It may be food for thought for a `Migrating to Red Hat OpenJDK from Oracle JDK` doc module :)

**Comment by mgm3746** [comment]
Can we close this out and create a new issue for creating a Migrating to Red Hat OpenJDK from Oracle JDK module?

**Comment by ncbaratta** [comment]
Sure, I'd enter that new issue as a docs JIRA.

**Comment by mgm3746** [comment]
I opened the following documentation Jira:
https://issues.jboss.org/projects/OPENJDK/issues/OPENJDK-44?
